[2025-06-07T20:21:14.256+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-07T20:21:13.781926+00:00 [queued]>
[2025-06-07T20:21:14.264+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-07T20:21:13.781926+00:00 [queued]>
[2025-06-07T20:21:14.265+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-07T20:21:14.279+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_deep_hybrid_model> on 2025-06-07 20:21:13.781926+00:00
[2025-06-07T20:21:14.286+0000] {standard_task_runner.py:60} INFO - Started process 1284 to run task
[2025-06-07T20:21:14.292+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deep_models_pipeline', 'train_deep_hybrid_model', 'manual__2025-06-07T20:21:13.781926+00:00', '--job-id', '2603', '--raw', '--subdir', 'DAGS_FOLDER/train_deep_model_dag.py', '--cfg-path', '/tmp/tmpz25zxoqt']
[2025-06-07T20:21:14.294+0000] {standard_task_runner.py:88} INFO - Job 2603: Subtask train_deep_hybrid_model
[2025-06-07T20:21:14.335+0000] {task_command.py:423} INFO - Running <TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-07T20:21:13.781926+00:00 [running]> on host 78208c00c095
[2025-06-07T20:21:14.414+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deep_models_pipeline' AIRFLOW_CTX_TASK_ID='train_deep_hybrid_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T20:21:13.781926+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-07T20:21:13.781926+00:00'
[2025-06-07T20:21:14.415+0000] {train_deep_model_dag.py:13} INFO - üü¶ Running command: python /opt/***/src/models/train_hybrid_deep_model.py --n_neighbors=38 --latent_dim=32 --epochs=80 --tfidf_features=1833
[2025-06-07T20:23:00.269+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-06-07T20:23:00.272+0000] {process_utils.py:131} INFO - Sending 15 to group 1284. PIDs of all processes in the group: [1292, 1284]
[2025-06-07T20:23:00.272+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1284
[2025-06-07T20:23:00.274+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-07T20:23:00.312+0000] {train_deep_model_dag.py:32} ERROR - ‚ùå Subprozess-Ausnahme: Task received SIGTERM signal
[2025-06-07T20:23:00.326+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1292, status='terminated', started='20:21:13') (1292) terminated with exit code None
[2025-06-07T20:23:00.341+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1284, status='terminated', exitcode=0, started='20:21:13') (1284) terminated with exit code 0
