[2025-06-06T20:49:40.022+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-06T20:49:35.195677+00:00 [queued]>
[2025-06-06T20:49:40.030+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-06T20:49:35.195677+00:00 [queued]>
[2025-06-06T20:49:40.030+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-06T20:49:40.040+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_deep_hybrid_model> on 2025-06-06 20:49:35.195677+00:00
[2025-06-06T20:49:40.046+0000] {standard_task_runner.py:60} INFO - Started process 842 to run task
[2025-06-06T20:49:40.048+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deep_models_pipeline', 'train_deep_hybrid_model', 'manual__2025-06-06T20:49:35.195677+00:00', '--job-id', '2272', '--raw', '--subdir', 'DAGS_FOLDER/train_deep_model_dag.py', '--cfg-path', '/tmp/tmp36mlcycj']
[2025-06-06T20:49:40.049+0000] {standard_task_runner.py:88} INFO - Job 2272: Subtask train_deep_hybrid_model
[2025-06-06T20:49:40.082+0000] {task_command.py:423} INFO - Running <TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-06T20:49:35.195677+00:00 [running]> on host e69802a76489
[2025-06-06T20:49:40.144+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deep_models_pipeline' AIRFLOW_CTX_TASK_ID='train_deep_hybrid_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T20:49:35.195677+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T20:49:35.195677+00:00'
[2025-06-06T20:49:40.145+0000] {train_deep_model_dag.py:13} INFO - üü¶ Running command: python /opt/***/src/models/train_hybrid_deep_model.py --n_neighbors=10 --latent_dim=32 --epochs=30 --tfidf_features=300
[2025-06-06T20:49:55.155+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-06-06T20:49:55.157+0000] {process_utils.py:131} INFO - Sending 15 to group 842. PIDs of all processes in the group: [845, 842]
[2025-06-06T20:49:55.157+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 842
[2025-06-06T20:49:55.159+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-06T20:49:55.187+0000] {train_deep_model_dag.py:32} ERROR - ‚ùå Subprozess-Ausnahme: Task received SIGTERM signal
[2025-06-06T20:49:55.211+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=842, status='terminated', exitcode=0, started='20:49:39') (842) terminated with exit code 0
[2025-06-06T20:49:55.213+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=845, status='terminated', started='20:49:39') (845) terminated with exit code None
