[2025-06-02T05:55:03.452+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_recommendation_pipeline.dvc_pull_all manual__2025-06-02T05:49:25.287870+00:00 [queued]>
[2025-06-02T05:55:03.459+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_recommendation_pipeline.dvc_pull_all manual__2025-06-02T05:49:25.287870+00:00 [queued]>
[2025-06-02T05:55:03.459+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-02T05:55:03.470+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dvc_pull_all> on 2025-06-02 05:49:25.287870+00:00
[2025-06-02T05:55:03.474+0000] {standard_task_runner.py:60} INFO - Started process 1115 to run task
[2025-06-02T05:55:03.477+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'movie_recommendation_pipeline', 'dvc_pull_all', 'manual__2025-06-02T05:49:25.287870+00:00', '--job-id', '1512', '--raw', '--subdir', 'DAGS_FOLDER/mlops_movie_dag.py', '--cfg-path', '/tmp/tmp_133rq8_']
[2025-06-02T05:55:03.478+0000] {standard_task_runner.py:88} INFO - Job 1512: Subtask dvc_pull_all
[2025-06-02T05:55:03.510+0000] {task_command.py:423} INFO - Running <TaskInstance: movie_recommendation_pipeline.dvc_pull_all manual__2025-06-02T05:49:25.287870+00:00 [running]> on host 0e6e1ff1f8df
[2025-06-02T05:55:03.562+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movie_recommendation_pipeline' AIRFLOW_CTX_TASK_ID='dvc_pull_all' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T05:49:25.287870+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-02T05:49:25.287870+00:00'
[2025-06-02T05:55:03.563+0000] {mlops_movie_dag.py:12} INFO - üü¶ Running command: dvc pull /opt/***/models/hybrid_model.pkl
[2025-06-02T05:55:13.275+0000] {mlops_movie_dag.py:19} INFO - üü© [stdout]:
Everything is up to date.

[2025-06-02T05:55:13.276+0000] {mlops_movie_dag.py:12} INFO - üü¶ Running command: dvc pull /opt/***/data/processed/hybrid_matrix.csv
[2025-06-02T05:55:22.919+0000] {mlops_movie_dag.py:19} INFO - üü© [stdout]:
Everything is up to date.

[2025-06-02T05:55:22.920+0000] {mlops_movie_dag.py:12} INFO - üü¶ Running command: dvc pull /opt/***/data/processed/hybrid_matrix_features.txt
[2025-06-02T05:55:25.780+0000] {mlops_movie_dag.py:19} INFO - üü© [stdout]:

[2025-06-02T05:55:25.781+0000] {mlops_movie_dag.py:21} WARNING - üü® [stderr]:
ERROR: failed to pull data from the cloud - Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.

[2025-06-02T05:55:25.781+0000] {mlops_movie_dag.py:29} ERROR - ‚ùå Subprozess-Fehler (exit code 1): dvc pull /opt/***/data/processed/hybrid_matrix_features.txt
[2025-06-02T05:55:25.781+0000] {mlops_movie_dag.py:32} ERROR - ‚ùå Subprozess-Ausnahme: Command '['dvc', 'pull', '/opt/***/data/processed/hybrid_matrix_features.txt']' returned non-zero exit status 1.
[2025-06-02T05:55:25.782+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mlops_movie_dag.py", line 139, in dvc_pull_all
    run_and_log(["dvc", "pull", art])
  File "/opt/airflow/dags/mlops_movie_dag.py", line 30, in run_and_log
    raise subprocess.CalledProcessError(result.returncode, command)
subprocess.CalledProcessError: Command '['dvc', 'pull', '/opt/airflow/data/processed/hybrid_matrix_features.txt']' returned non-zero exit status 1.
[2025-06-02T05:55:25.792+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=movie_recommendation_pipeline, task_id=dvc_pull_all, execution_date=20250602T054925, start_date=20250602T055503, end_date=20250602T055525
[2025-06-02T05:55:25.822+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1512 for task dvc_pull_all (Command '['dvc', 'pull', '/opt/airflow/data/processed/hybrid_matrix_features.txt']' returned non-zero exit status 1.; 1115)
[2025-06-02T05:55:25.848+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-02T05:55:25.866+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
