[2025-06-07T21:43:28.531+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-07T21:43:27.879449+00:00 [queued]>
[2025-06-07T21:43:28.540+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-07T21:43:27.879449+00:00 [queued]>
[2025-06-07T21:43:28.541+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-07T21:43:28.554+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_deep_hybrid_model> on 2025-06-07 21:43:27.879449+00:00
[2025-06-07T21:43:28.562+0000] {standard_task_runner.py:60} INFO - Started process 208 to run task
[2025-06-07T21:43:28.565+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deep_models_pipeline', 'train_deep_hybrid_model', 'manual__2025-06-07T21:43:27.879449+00:00', '--job-id', '2660', '--raw', '--subdir', 'DAGS_FOLDER/train_deep_model_dag.py', '--cfg-path', '/tmp/tmp4__qso6s']
[2025-06-07T21:43:28.567+0000] {standard_task_runner.py:88} INFO - Job 2660: Subtask train_deep_hybrid_model
[2025-06-07T21:43:28.612+0000] {task_command.py:423} INFO - Running <TaskInstance: deep_models_pipeline.train_deep_hybrid_model manual__2025-06-07T21:43:27.879449+00:00 [running]> on host 19985e64f4e7
[2025-06-07T21:43:28.692+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deep_models_pipeline' AIRFLOW_CTX_TASK_ID='train_deep_hybrid_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T21:43:27.879449+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-07T21:43:27.879449+00:00'
[2025-06-07T21:43:28.694+0000] {train_deep_model_dag.py:13} INFO - üü¶ Running command: python /opt/***/src/models/train_hybrid_deep_model.py --n_neighbors=15 --latent_dim=32 --epochs=30 --tfidf_features=300
[2025-06-07T21:43:43.717+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-06-07T21:43:43.719+0000] {process_utils.py:131} INFO - Sending 15 to group 208. PIDs of all processes in the group: [213, 208]
[2025-06-07T21:43:43.720+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 208
[2025-06-07T21:43:43.721+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-07T21:43:43.753+0000] {train_deep_model_dag.py:32} ERROR - ‚ùå Subprozess-Ausnahme: Task received SIGTERM signal
[2025-06-07T21:43:43.773+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=213, status='terminated', started='21:43:28') (213) terminated with exit code None
[2025-06-07T21:43:43.774+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=208, status='terminated', exitcode=0, started='21:43:28') (208) terminated with exit code 0
