[2025-06-04T19:47:47.508+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deep_models_pipeline.validate_models manual__2025-06-04T19:41:20.934556+00:00 [queued]>
[2025-06-04T19:47:47.519+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deep_models_pipeline.validate_models manual__2025-06-04T19:41:20.934556+00:00 [queued]>
[2025-06-04T19:47:47.520+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-04T19:47:47.533+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_models> on 2025-06-04 19:41:20.934556+00:00
[2025-06-04T19:47:47.541+0000] {standard_task_runner.py:60} INFO - Started process 4389 to run task
[2025-06-04T19:47:47.543+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deep_models_pipeline', 'validate_models', 'manual__2025-06-04T19:41:20.934556+00:00', '--job-id', '1865', '--raw', '--subdir', 'DAGS_FOLDER/train_deep_model_dag.py', '--cfg-path', '/tmp/tmpr17vscw_']
[2025-06-04T19:47:47.545+0000] {standard_task_runner.py:88} INFO - Job 1865: Subtask validate_models
[2025-06-04T19:47:47.593+0000] {task_command.py:423} INFO - Running <TaskInstance: deep_models_pipeline.validate_models manual__2025-06-04T19:41:20.934556+00:00 [running]> on host 4d1325249967
[2025-06-04T19:47:47.671+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deep_models_pipeline' AIRFLOW_CTX_TASK_ID='validate_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T19:41:20.934556+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-04T19:41:20.934556+00:00'
[2025-06-04T19:47:47.672+0000] {train_deep_model_dag.py:13} INFO - 🟦 Running command: python /opt/***/src/models/validate_model.py --pipeline_type=dl --test_user_count=100
[2025-06-04T19:48:31.840+0000] {train_deep_model_dag.py:20} INFO - 🟩 [stdout]:
🏃 View run validate_predictions_dl at: https://dagshub.com/sacer11/MLOps_movie_rec_apr25.mlflow/#/experiments/3/runs/38a83e2619854976888864a783a55853
🧪 View experiment at: https://dagshub.com/sacer11/MLOps_movie_rec_apr25.mlflow/#/experiments/3

[2025-06-04T19:48:31.842+0000] {train_deep_model_dag.py:22} WARNING - 🟨 [stderr]:
2025-06-04 19:47:50,057 - INFO - 🚀 Starte Validierung (DL)
2025-06-04 19:48:00,236 - INFO - 📥 Daten & Modelle geladen – Beginne Evaluation
2025-06-04 19:48:14,517 - WARNING - ⚠️ Fehler bei User 51: 51
2025-06-04 19:48:25,817 - WARNING - ⚠️ Fehler bei User 91: 91
2025-06-04 19:48:28,448 - INFO - 📊 precision_10_hybrid: 0.21
2025-06-04 19:48:28,448 - INFO - 📊 precision_10_user:   0.05
2025-06-04 19:48:31,417 - INFO - 🎉 Validation abgeschlossen.

[2025-06-04T19:48:31.842+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-04T19:48:31.859+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=deep_models_pipeline, task_id=validate_models, execution_date=20250604T194120, start_date=20250604T194747, end_date=20250604T194831
[2025-06-04T19:48:31.913+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-04T19:48:31.937+0000] {taskinstance.py:3280} INFO - 2 downstream tasks scheduled from follow-on schedule check
