[2025-06-06T00:56:02.383+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deep_models_pipeline.dvc_pull_bestmodels manual__2025-06-06T00:51:52.792868+00:00 [queued]>
[2025-06-06T00:56:02.390+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deep_models_pipeline.dvc_pull_bestmodels manual__2025-06-06T00:51:52.792868+00:00 [queued]>
[2025-06-06T00:56:02.390+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2025-06-06T00:56:02.400+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dvc_pull_bestmodels> on 2025-06-06 00:51:52.792868+00:00
[2025-06-06T00:56:02.408+0000] {standard_task_runner.py:60} INFO - Started process 2299 to run task
[2025-06-06T00:56:02.410+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deep_models_pipeline', 'dvc_pull_bestmodels', 'manual__2025-06-06T00:51:52.792868+00:00', '--job-id', '2124', '--raw', '--subdir', 'DAGS_FOLDER/train_deep_model_dag.py', '--cfg-path', '/tmp/tmpq8r3_6ka']
[2025-06-06T00:56:02.412+0000] {standard_task_runner.py:88} INFO - Job 2124: Subtask dvc_pull_bestmodels
[2025-06-06T00:56:02.451+0000] {task_command.py:423} INFO - Running <TaskInstance: deep_models_pipeline.dvc_pull_bestmodels manual__2025-06-06T00:51:52.792868+00:00 [running]> on host 26ba7f5980a4
[2025-06-06T00:56:02.512+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deep_models_pipeline' AIRFLOW_CTX_TASK_ID='dvc_pull_bestmodels' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T00:51:52.792868+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T00:51:52.792868+00:00'
[2025-06-06T00:56:02.514+0000] {train_deep_model_dag.py:13} INFO - üü¶ Running command: dvc pull /opt/***/models/hybrid_deep_model.pkl
[2025-06-06T00:56:19.033+0000] {train_deep_model_dag.py:20} INFO - üü© [stdout]:

[2025-06-06T00:56:19.033+0000] {train_deep_model_dag.py:22} WARNING - üü® [stderr]:
WARNING: failed to collect 'workspace', skipping
ERROR: failed to pull data from the cloud - '/opt/***/models/hybrid_deep_model.pkl' does not exist as an output or a stage name in 'dvc.yaml': 'dvc.yaml' does not exist

[2025-06-06T00:56:19.034+0000] {train_deep_model_dag.py:29} ERROR - ‚ùå Subprozess-Fehler (exit code 1): dvc pull /opt/***/models/hybrid_deep_model.pkl
[2025-06-06T00:56:19.034+0000] {train_deep_model_dag.py:32} ERROR - ‚ùå Subprozess-Ausnahme: Command '['dvc', 'pull', '/opt/***/models/hybrid_deep_model.pkl']' returned non-zero exit status 1.
[2025-06-06T00:56:19.034+0000] {train_deep_model_dag.py:84} ERROR - ‚ùå Unerwarteter Fehler beim DVC-Pull f√ºr /opt/***/models/hybrid_deep_model.pkl: Command '['dvc', 'pull', '/opt/***/models/hybrid_deep_model.pkl']' returned non-zero exit status 1.
[2025-06-06T00:56:19.035+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/train_deep_model_dag.py", line 74, in dvc_pull_bestmodels_dl
    run_and_log(["dvc", "pull", art])
  File "/opt/airflow/dags/train_deep_model_dag.py", line 30, in run_and_log
    raise subprocess.CalledProcessError(result.returncode, command)
subprocess.CalledProcessError: Command '['dvc', 'pull', '/opt/airflow/models/hybrid_deep_model.pkl']' returned non-zero exit status 1.
[2025-06-06T00:56:19.047+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=deep_models_pipeline, task_id=dvc_pull_bestmodels, execution_date=20250606T005152, start_date=20250606T005602, end_date=20250606T005619
[2025-06-06T00:56:19.058+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2124 for task dvc_pull_bestmodels (Command '['dvc', 'pull', '/opt/airflow/models/hybrid_deep_model.pkl']' returned non-zero exit status 1.; 2299)
[2025-06-06T00:56:19.087+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-06T00:56:19.102+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
